import './genericwallet.spec';
import './liskLikeWallet.spec';
import './transactions/basetx.spec';
import './transactions/delegate.spec';
import './transactions/secondSignature.spec';
import './transactions/send.spec';
import './transactions/sendWithDataField.spec';
import './transactions/vote.spec';
import './utils/txFactory.spec';
